"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-21 11:54:27.392220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coe_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('JIRA', 'WIZ', 'CROWDSTRIKE', 'VIBRANIUM', name='source_enum'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'UNKNOWN', name='coe_severity'), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('manager_email', sa.String(length=255), nullable=True),
    sa.Column('missing_owner_in_hr', sa.Boolean(), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=32), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('coe_review_status', sa.String(length=64), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_coe_events_source_sourceid')
    )
    op.create_index(op.f('ix_coe_events_owner_email'), 'coe_events', ['owner_email'], unique=False)
    op.create_index(op.f('ix_coe_events_severity'), 'coe_events', ['severity'], unique=False)
    op.create_index(op.f('ix_coe_events_source'), 'coe_events', ['source'], unique=False)
    op.create_index(op.f('ix_coe_events_source_id'), 'coe_events', ['source_id'], unique=False)
    op.create_table('coe_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('events_ingested', sa.Integer(), nullable=False),
    sa.Column('is_bootstrap', sa.Boolean(), nullable=False),
    sa.Column('errors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crowdstrike_raw',
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('source_id', 'fetched_at')
    )
    op.create_table('employees',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('manager_email', sa.String(length=255), nullable=True),
    sa.Column('org_path', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('jira_raw',
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('source_id', 'fetched_at')
    )
    op.create_table('vibranium_raw',
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('source_id', 'fetched_at')
    )
    op.create_table('wiz_raw',
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('source_id', 'fetched_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wiz_raw')
    op.drop_table('vibranium_raw')
    op.drop_table('jira_raw')
    op.drop_table('employees')
    op.drop_table('crowdstrike_raw')
    op.drop_table('coe_runs')
    op.drop_index(op.f('ix_coe_events_source_id'), table_name='coe_events')
    op.drop_index(op.f('ix_coe_events_source'), table_name='coe_events')
    op.drop_index(op.f('ix_coe_events_severity'), table_name='coe_events')
    op.drop_index(op.f('ix_coe_events_owner_email'), table_name='coe_events')
    op.drop_table('coe_events')
    # ### end Alembic commands ###
