"""coe_runs.doc_url

Revision ID: 0002
Revises: 0001
Create Date: 2026-05-21 15:27:01.319627

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coe_runs', sa.Column('doc_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coe_runs', 'doc_url')
    # ### end Alembic commands ###
